name: Residence
main: com.bekvon.bukkit.residence.ResidenceCommandListener
version: 2.6.6.4
description: Cuboid Residence Plugin
authors: [bekvon,nate302,t00thpick1]
contributors: [lemon42,smbarbour,inorixu,Shayana_fr]
softdepend: [Vault,Essentials,RealPlugin,BOSEconomy,iConomy,bPermissions,PermissionsBukkit,Permissions,WorldEdit,My Worlds]
commands:
  res:
    description: Manage Residences
    usage: §c/res ? for more info
  residence:
    description: Manage Residences
    usage: §c/residence ? for more info
  resadmin:
    description: Residence admin functions.
    usage: §c/res ? or /resadmin ? for more info
  resreload:
    description: Reload the entire residence plugin.
    usage: §c/resreload
  resload:
    description: Load the save file again after you have made modifications.
    usage: §c/resload
  rc:
    description: §cChat in current residence channel.
    usage: §c/rc to toggle, or /rc <message>
  resworld:
    description: §cRemoves every residence in a world.
    usage: §c/resworld remove [world]
permissions:
  residence.admin:
    description: Gives you access to /resadmin
    default: op
  residence.admin.tp:
    description: Allows to override tp flag
    default: op
  residence.admin.move:
    description: Allows to override move flag
    default: op
  residence.create:
    description: Allows you to create residences
    default: op
  residence.select:
    description: Allows you to select an area to make residences
    default: op
