name: Residence
main: com.bekvon.bukkit.residence.Residence
version: 2.5.1
description: Cuboid Residence Plugin
author: bekvon
softdepend: [Vault]
commands:
  res:
    description: Manage Residences
    usage: §c/res ? for more info
  residence:
    description: Manage Residences
    usage: §c/residence ? for more info
  resadmin:
    description: Residence admin functions.
    usage: §c/res ? or /resadmin ? for more info
  resreload:
    description: Reload the entire residence plugin.
    usage: §c/resreload
  resload:
    description: Load the save file again after you have made modifications.
    usage: §c/resload
  rc:
    description: §cChat in current residence channel.
    usage: §c/rc to toggle, or /rc <message>
  resworld:
    description: §cRemoves every residence in a world.
    usage: §c/resworld remove [world]
permissions:
  residence.admin:
    description: Gives you access to /resadmin
    default: op
  residence.create:
    description: Allows you to create residences
    default: op