name: Residence
main: com.bekvon.bukkit.residence.ResidenceCommandListener
version: 2.9.7.1
website: https://www.spigotmc.org/resources/residence.11480/
description: Cuboid Residence Plugin
authors: [bekvon,nate302,t00thpick1]
softdepend: [Vault,Essentials,RealPlugin,BOSEconomy,iConomy,bPermissions,PermissionsBukkit,Permissions,WorldEdit,WorldGuard,CrackShot,My Worlds]
contributors: [lemon42,smbarbour,inorixu,Shayana_fr]
commands:
  res:
    description: Manage Residences
    usage: §c/res ? for more info
  residence:
    description: Manage Residences
    usage: §c/residence ? for more info
  resadmin:
    description: Residence admin functions.
    usage: §c/res ? or /resadmin ? for more info
  resreload:
    description: Reload the entire residence plugin.
    usage: §c/resreload
  resload:
    description: Load the save file again after you have made modifications.
    usage: §c/resload
  rc:
    description: §cChat in current residence channel.
    usage: §c/rc §eto toggle, §c/rc l §eto leave, §c/rc setprefix §eto set prefix, §c/rc setcolor §eto set color or §c/rc kick §eto kick player
  resworld:
    description: §cRemoves every residence in a world.
    usage: §c/resworld remove [world]
  ressignconvert:
    description: §cConverts signs from ResidenceSigns plugin.
    usage: §c/ressignconvert
permissions:
  residence.admin:
    description: Gives you access to /resadmin
    default: op
  residence.topadmin:
    description: Gives you access to /resreload and /resload commands
    default: op
  residence.admin.tp:
    description: Allows to override tp flag
    default: op
  residence.admin.move:
    description: Allows to override move flag
    default: op
  residence.create:
    description: Allows you to create residences
    default: true
  residence.select:
    description: Allows you to select an area to make residences
    default: true
  residence.versioncheck:
    description: Notice to new version after connect
    default: op
  residence.nofly.bypass:
    description: Bypasses nofly flag in residence
    default: op
  residence.flag.command.bypass:
    description: Bypasses command flag in residence
    default: op
  residence.select.auto.others:
    description: Allows to turn on auto selection for other players
    default: op
  residence.chatcolor:
    description: Allows to change residence chat color
    default: true
  residence.chatprefix:
    description: Allows to change residence chat prefix
    default: op
  residence.chatkick:
    description: Allows to kick players from residence chat
    default: true
  residence.compass:
    description: Allows to set compass pointer to residence
    default: true
  residence.randomtp:
    description: Allows to use /res rt command
    default: true
